# Generated by Django 5.1.5 on 2026-06-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_questionhistory_options_chatsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='page_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
