# Generated by Django 5.1.5 on 2026-07-06 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentchunk_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunk_overlap',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='document',
            name='chunk_size',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='document',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('pending_processing', 'Pending Processing'), ('extracting_text', 'Extracting Text'), ('chunking', 'Chunking'), ('indexing', 'Indexing Vectors'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questionhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='VectorIndexMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faiss_index_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_mappings', to='documents.documentchunk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_mappings', to='documents.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'faiss_index_id'], name='documents_v_documen_038681_idx'), models.Index(fields=['chunk'], name='documents_v_chunk_i_37023a_idx')],
                'unique_together': {('document', 'faiss_index_id')},
            },
        ),
    ]
