# Generated by Django 5.1.5 on 2026-07-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_chunk_overlap_document_chunk_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('pending_processing', 'Pending Processing'), ('processing', 'Processing'), ('extracting_text', 'Extracting Text'), ('chunking', 'Chunking'), ('indexing', 'Indexing Vectors'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
    ]
